# Generated by Django 6.0.1 on 2026-02-23 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('tradein', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tradein_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tradein.tradeinrequest'),
        ),
    ]
