# Generated by Django 6.0.1 on 2026-01-24 16:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text='Tên máy cũ (VD: Iphone 11)', max_length=255)),
                ('is_power_on', models.BooleanField(default=True, verbose_name='Nguồn còn lên')),
                ('screen_ok', models.BooleanField(default=True, verbose_name='Màn hình không vỡ')),
                ('body_ok', models.BooleanField(default=True, verbose_name='Vỏ đẹp, không cấn móp')),
                ('battery_percentage', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('SUBMITTED', 'Đã gửi'), ('APPROVED', 'Đã duyệt')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
