# Generated by Django 6.0.1 on 2026-03-01 11:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_refund_refunditem_alter_order_options_and_more'),
        ('products', '0003_alter_product_main_image'),
        ('tradein', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeInImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tradeins/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeInPriceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('storage', models.CharField(blank=True, max_length=50)),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('power_off_deduction', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('screen_broken_deduction', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('body_damage_deduction', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('battery_below_80_deduction', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('battery_below_60_deduction', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='TradeInTempImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(db_index=True)),
                ('image', models.ImageField(upload_to='tradein_temp/')),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tradeinrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='tradeinrequest',
            name='device_name',
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand'),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='staff_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='storage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='target_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tradein_targets', to='products.product'),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='tradein_type',
            field=models.CharField(blank=True, choices=[('SELL', 'Bán lại'), ('EXCHANGE', 'Thu cũ đổi mới')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tradeinrequest',
            name='battery_percentage',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tradeinrequest',
            name='body_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tradeinrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tradeinrequest',
            name='is_power_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tradeinrequest',
            name='screen_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tradeinrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ tới cửa hàng'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('CANCELLED', 'Đã hủy'), ('COMPLETED', 'Hoàn tất')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tradeins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tradeinrequest',
            index=models.Index(fields=['user', '-created_at'], name='tradein_tra_user_id_60ce8f_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeinrequest',
            index=models.Index(fields=['status', 'tradein_type'], name='tradein_tra_status_5c8d33_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeinrequest',
            index=models.Index(fields=['status', '-created_at'], name='tradein_tra_status_3a1a84_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeinrequest',
            index=models.Index(fields=['status', 'expires_at'], name='tradein_tra_status_1a021c_idx'),
        ),
        migrations.AddField(
            model_name='exchangeorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_order', to='orders.order'),
        ),
        migrations.AddField(
            model_name='exchangeorder',
            name='tradein_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_order', to='tradein.tradeinrequest'),
        ),
        migrations.AddField(
            model_name='tradeinimage',
            name='tradein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tradein.tradeinrequest'),
        ),
        migrations.AddField(
            model_name='tradeinpriceconfig',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.brand'),
        ),
        migrations.AddField(
            model_name='tradeinpriceconfig',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category'),
        ),
        migrations.AddIndex(
            model_name='tradeintempimage',
            index=models.Index(fields=['session_key', 'is_used'], name='tradein_tra_session_e4f200_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tradeinpriceconfig',
            unique_together={('brand', 'category', 'model_name', 'storage')},
        ),
    ]
