# Generated by Django 5.2.14 on 2026-05-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_svg',
            field=models.TextField(blank=True, help_text='Dán mã code <svg>...</svg> vào đây', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image_url',
            field=models.URLField(blank=True, help_text='Link ảnh từ nguồn ngoài', max_length=500, null=True),
        ),
    ]
