# Generated by Django 5.2.14 on 2026-05-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brand_logo_svg_product_main_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo_svg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_image_url',
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.TextField(blank=True, help_text='Tải ảnh lên hoặc dán mã SVG', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.TextField(blank=True, help_text='Tải ảnh lên hoặc dán Link ảnh online', null=True),
        ),
    ]
