# Generated by Django 5.2.14 on 2026-05-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_brand_logo_svg_remove_product_main_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_svg',
            field=models.TextField(blank=True, help_text='Dán mã SVG', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image_url',
            field=models.TextField(blank=True, help_text='Link ảnh online', null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
