# Generated by Django 5.2.14 on 2026-05-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_brand_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='battery_health',
        ),
    ]
