# Generated by Django 5.2.14 on 2026-05-30 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_product_ram_product_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('url_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đường dẫn URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('embedding', models.JSONField(blank=True, null=True, verbose_name='Vector Embedding (JSON)')),
            ],
            options={
                'verbose_name': 'Tài liệu Website',
                'verbose_name_plural': 'Tài liệu Website',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True, verbose_name='Mã phiên chat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Phiên Chat',
                'verbose_name_plural': 'Phiên Chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Khách hàng'), ('bot', 'Trợ lý ảo')], max_length=10, verbose_name='Người gửi')),
                ('message', models.TextField(verbose_name='Tin nhắn')),
                ('citations', models.JSONField(blank=True, null=True, verbose_name='Tài liệu tham chiếu (Citations)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession', verbose_name='Phiên chat')),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Tin nhắn',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(blank=True, null=True, verbose_name='Vector Embedding (JSON)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_embedding', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Embedding Sản phẩm',
                'verbose_name_plural': 'Embedding Sản phẩm',
            },
        ),
    ]
