# Generated by Django 6.0.1 on 2026-03-01 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_refund_refunditem_alter_order_options_and_more'),
        ('tradein', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('ORDER', 'Thanh toán đơn hàng'), ('TRADEIN_SELL_PAYOUT', 'Chi trả trade-in (bán lại)'), ('TRADEIN_EXCHANGE', 'Thanh toán trade-in (đổi máy)')], db_index=True, max_length=30)),
                ('payment_method', models.CharField(choices=[('CASH', 'Tiền mặt'), ('BANK_TRANSFER', 'Chuyển khoản ngân hàng'), ('COD', 'Thanh toán khi nhận hàng')], max_length=20)),
                ('direction', models.CharField(choices=[('INBOUND', 'User trả tiền cho cửa hàng'), ('OUTBOUND', 'Cửa hàng trả tiền cho User')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('COMPLETED', 'Hoàn tất'), ('FAILED', 'Thất bại'), ('REFUNDED', 'Đã hoàn tiền')], db_index=True, default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('transaction_ref', models.CharField(blank=True, max_length=255)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
                ('tradein_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tradein.tradeinrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payment_pay_user_id_2df5ec_idx'), models.Index(fields=['status', 'payment_type'], name='payment_pay_status_70c1d8_idx'), models.Index(fields=['tradein_request', 'status'], name='payment_pay_tradein_3b4927_idx'), models.Index(fields=['order', 'status'], name='payment_pay_order_i_b37863_idx')],
            },
        ),
    ]
