# Generated by Django 6.0.1 on 2026-03-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Tiền mặt'), ('BANK_TRANSFER', 'Chuyển khoản ngân hàng'), ('COD', 'Thanh toán khi nhận hàng'), ('ZALOPAY', 'Ví ZaloPay')], max_length=20),
        ),
    ]
