# Generated by Django 5.2.14 on 2026-05-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Tiền mặt'), ('COD', 'Thanh toán khi nhận hàng'), ('ZALOPAY', 'Ví ZaloPay')], max_length=20),
        ),
    ]
