# Generated by Django 5.2.14 on 2026-05-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('ORDER', 'Thanh toán đơn hàng'), ('TRADEIN_SELL_PAYOUT', 'Chi trả trade-in (bán lại)')], db_index=True, max_length=30),
        ),
    ]
