# Generated by Django 6.0.1 on 2026-01-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_product_order_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
