# Generated by Django 5.2.14 on 2026-05-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradein', '0003_exchangeorder_tradeinimage_tradeinpriceconfig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeinpriceconfig',
            name='battery_below_60_deduction',
        ),
        migrations.RemoveField(
            model_name='tradeinpriceconfig',
            name='battery_below_80_deduction',
        ),
        migrations.RemoveField(
            model_name='tradeinrequest',
            name='battery_percentage',
        ),
    ]
