# Generated by Django 5.2.14 on 2026-05-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradein', '0004_remove_tradeinpriceconfig_battery_below_60_deduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeinrequest',
            name='target_product',
        ),
        migrations.AlterField(
            model_name='tradeinrequest',
            name='tradein_type',
            field=models.CharField(blank=True, choices=[('SELL', 'Bán lại')], db_index=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ExchangeOrder',
        ),
    ]
