# Generated by Django 5.2.14 on 2026-05-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradein', '0005_remove_tradeinrequest_target_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeinpriceconfig',
            name='body_damage_deduction',
        ),
        migrations.RemoveField(
            model_name='tradeinpriceconfig',
            name='screen_broken_deduction',
        ),
        migrations.RemoveField(
            model_name='tradeinrequest',
            name='body_ok',
        ),
        migrations.RemoveField(
            model_name='tradeinrequest',
            name='screen_ok',
        ),
        migrations.AddField(
            model_name='tradeinpriceconfig',
            name='body',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='tradeinpriceconfig',
            name='screen',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='body',
            field=models.CharField(default='good', max_length=50),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='screen',
            field=models.CharField(default='good', max_length=50),
        ),
    ]
