# Generated by Django 5.2.14 on 2026-05-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradein', '0006_remove_tradeinpriceconfig_body_damage_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeinrequest',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
