# Generated by Django 5.2.14 on 2026-05-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_ram_product_storage'),
        ('tradein', '0007_tradeinrequest_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tradeinpriceconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tradeinpriceconfig',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeinpriceconfig',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tradeinpriceconfig',
            unique_together={('brand', 'category', 'model_name', 'storage', 'ram')},
        ),
    ]
