# Generated by Django 5.2.14 on 2026-05-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.TextField(blank=True, help_text='Dán mã code <svg>...</svg> vào đây', null=True),
        ),
    ]
