# Generated by Django 5.2.14 on 2026-05-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_brand_logo_svg_product_main_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
